### ISSUE TITLE
AWX trusted origins Django CSRF_TRUSTED_ORIGINS issue on Github Codespaces

### ISSUE THREAD

**Issue by star3am** [star3am/hashiqube#75]
When I run AWX Tower on Github Codespaces I am unable to login 

Ref: https://github.com/ansible/awx/issues/14024

**Comment by star3am** [comment]
Ref: https://stackoverflow.com/questions/38841109/csrf-validation-does-not-work-on-django-using-https

**Comment by star3am** [comment]
Fixed with: 
```
extra_settings:
  - setting: CSRF_TRUSTED_ORIGINS
    value:
      - https://$CODESPACE_NAME-8043.app.github.dev
      - $CODESPACE_NAME-8043.app.github.dev
  - setting: SECURE_PROXY_SSL_HEADER
    value:
      - HTTP_X_FORWARDED_PROTO
      - https
```
